language: c

addons:
  apt:
    packages:
      - libjava3d-java

install:
    - make -Cdeps mason

script:
    - mkdir ./build
    - cmake -Bbuild -H.
    - make -Cbuild -j2
    - BACKENDS="c mason" ./test.sh
